config/routes.rb
Became::Application.routes.draw do

  get "funds/create"

  root to: 'pages#home'

  match "/info" => "pages#info"
  
  resources :students, only: [:new, :create, :show, :edit, :update] do
    resources :projects, only: [:new, :edit, :create, :update]
  end
  
  resources :projects, only: [:show, :index] do
    resources :funds, only: [:create]
  end
  
  resources :angels, only: [:new, :create, :show, :edit, :update]
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }
  
end

app/models/angel.rb
class Angel < ActiveRecord::Base
  acts_as_user
  attr_accessible :name, :user_attributes
  
  has_many :funds, dependent: :destroy
  has_many :projects, through: :funds
  
  accepts_nested_attributes_for :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :projects
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  attr_accessible :amount
  
  belongs_to :project, counter_cache: "angels_count"
  belongs_to :angel

  before_save :update_funded_counter
  before_destroy :update_funded_counter

  def update_funded_counter
    self.project.update_attribute :funded_count, self.project.funds.sum(:amount)+self.amount
  end


end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :finish_date, :goal, :title, :category_id, :why, :dreams, :abilities, :better_country

  belongs_to :student
  
  has_many :funds, dependent: :destroy
  has_many :angels, through: :funds
  
  belongs_to :category
  validates_numericality_of :goal

  default_scope where("finish_date >= ?", Date.today)

  def days_left
    if self.finish_date
      (self.finish_date - Date.today).to_i
    else
      0
    end
  end

  def current_percentage
    (self.funded_count * 100 / self.goal).to_i
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  acts_as_user
  attr_accessible :birthdate, :grade, :name, :surname, :user_attributes, :gender
  
  accepts_nested_attributes_for :user
  
  has_many :projects, dependent: :destroy
  
  def image
    "http://graph.facebook.com/#{self.uid}/picture?type=large"
  end

  def full_name
    "#{self.name} #{self.surname}"    
  end
end

app/models/user.rb
#encoding: utf-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :state, :city, :bio
  # attr_accessible :title, :body
  
  belongs_to :userable, polymorphic: true
  
  STATES = ["Aguascalientes", "Baja California", "Baja California Sur", 
             "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", 
             "Distrito", "Federal", "Durango", "Estado de México", "Guanajuato", 
             "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", 
             "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", 
             "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", 
             "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"]
  
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
        first_name = auth["extra"]["raw_info"].try("[]", "first_name")
        birthday = Date.strptime auth["extra"]["raw_info"]["birthday"], "%m/%d/%Y" if auth["extra"].try("[]", "raw_info").try("[]", "birthday")
        gender = auth["extra"].try("[]", "raw_info").try("[]", "gender")
        student = Student.new(name: first_name, birthdate: birthday, gender: gender)
        student.save(validate: false) if user.new_record?
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth["info"].try("[]", "email")
        user.userable_type = "Student"
        user.userable_id = student.id if user.new_record?
        user.city = auth["info"]["location"].split(",")[0] unless auth["info"]["location"].nil?
        user.state = auth["info"]["location"].split(",")[1].strip unless auth["info"]["location"].nil?
    end
  end
  
  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
  
  def is_student?
    self.userable_type ==  "Student"
  end
  
  def is_angel?
    self.userable_type == "Angel"
  end
  
  
  
end

app/controllers/angels_controller.rb
class AngelsController < ApplicationController
  def new
    @angel = Angel.new
  end

  def create
    @angel = Angel.new(params[:angel])
    if @angel.save
      sign_in_and_redirect @angel.user
    else
      render :new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def broadcast(channel, hash)
    message = {:channel => channel, :data => hash}
    uri = URI.parse("http://gentle-waters-9528.herokuapp.com/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  
  def create
    @project = Project.find(params[:project_id])
    @fund = @project.funds.build(params[:fund])
    @fund.angel = current_user.userable
    if @fund.save
      redirect_to @fund.project, flash: {success: "Wohooo"}
    else
      redirect_to @fund.project, flash: {error: "Buuuuhh"}
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_student_url
    end
  end
  
  alias_method :facebook, :all
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def info
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    @projects = Project.includes(:student)
  end

  def new
    @student = current_user.userable
    @project = @student.projects.build
  end
  
  def create
    @student = current_user.userable
    @project = @student.projects.build(params[:project])
    if @project.save
      broadcast "/projects/new", {projects_count: Project.count}
      redirect_to @project
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    @fund = @project.funds.build
  end

  def edit
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def new
    @student = Student.new
  end
  
  def create
    @student = Student.new(params[:student])
    if @student.save
      sign_in_and_redirect @student.user
    else
      render :new
    end
  end
  
  def edit
    @student = Student.find(params[:id])
  end
  
  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      redirect_to :back
    else
      render :edit
    end
  end

  def show
  end
end

app/helpers/angels_helper.rb
module AngelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper  
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/angels/new.html.haml
%h1 Crear cuenta de ángel

.unit
  .container.auth_wrapper
    = form_for @angel do |f|
      .unit
        = f.label :name, "Nombre"
        = f.text_field :name, class: "inp"
        
      = f.fields_for :user do |u|
        = render partial: 'shared/user_fields', locals: { u: u }
      .unit
        = f.submit "Registrarme", class: "submit"

app/views/layouts/_footer.html.haml
.columns.on-2
  .column.fixed{style: "width:100px;"}
    &nbsp;
  .column.fixed{:style => "width:950px;"}
    .unit.botter
.unit.content 
  %p
    Powered by #{link_to "Icalia Labs", "http://icalialabs.com", target: "_blank"}

app/views/layouts/_header.html.haml
.column
  = image_tag "logo_becalia.png", class: "logo"
.column
  .container.auth_menu
    - if user_signed_in?
      = link_to "Salir", destroy_user_session_path, method: :delete
      - if current_user.is_student?
        = link_to "Agregar proyecto", new_student_project_path(current_user.userable), class: "proyecto"
      = link_to "Editar perfil", edit_student_path(current_user.userable)
      %span= "Hola "+current_user.userable.name
    - else
      = link_to "Iniciar sesión", new_user_session_path, class: "iniciar"
      = link_to "Soy estudiante", new_student_path, class: "iniciar"
      = link_to "Soy ángel", new_angel_path, class: "iniciar"

app/views/layouts/_menu.html.haml
.unit.menu
	%ul
		- if controller.controller_name == 'pages' && controller.action_name == 'home'
			%li.active
				= link_to "Inicio", root_path
		- else
			%li
				= link_to "Inicio", root_path

		- if controller.controller_name == 'projects'
			%li.active
				= link_to "Proyectos", projects_path
		- else
			%li
				= link_to "Proyectos", projects_path
				
		- if controller.controller_name == 'pages' && controller.action_name == 'info'
			%li.active
				= link_to "Datos", info_path
		- else
			%li
				= link_to "Datos", info_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Becalia
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
    = javascript_include_tag "application", "http://gentle-waters-9528.herokuapp.com/faye.js "

  .unit.header
    .container.wrapper.columns.on-2
      = render "layouts/header"
  
  .unit.body
    .container.wrapper.columns.on-2.same-height
      .column.fixed{style: "width:100px;"}
        .container.full-height{style: "padding-top:30px;"}
          = render "shared/apoyalos"
      .column.fixed{:style => "width:950px;"}
        .shaddy_right
        .shaddy_bot
        = render "layouts/menu"
        .unit
          .container.body_wrapper
            = yield

  .unit.footer
    .container.wrapper
      = render "layouts/footer"

app/views/pages/home.html.haml
= image_tag "landing_photo.jpg", style: "height:346px;"

%h1#count_up
	= "Actualmente apoyamos " + Project.count.to_s + " proyectos"

%h2.about
	¿Por qué lo hacemos?

.columns.on-2.about
	.container.shadow
		= image_tag "pitch.png", style: "height:778px;"

app/views/pages/info.html.haml
%h1
	Haz conciencia

#content_mapa
	%h2
		Beneficiarios de PRONABES en el año
		%span.year 2010
	#edo Posicionate sobre un estado
	#mx_map
	#seleccion_mapa 
		%input{type: "radio", value: "2006", name: "year"} Estadísticas 2006
		%br
		%input{type: "radio", value: "2008", name: "year"} Estadísticas 2008
		%br
		%input{type: "radio", value: "2010", name: "year"} Estadísticas 2010

#pronabes-chart

app/views/projects/_form.html.haml
.unit
  .container.project_form_wrapper
    = form_for [@student, @project] do |f|
      .columns.on-2
        .column.fixed{style: "width:200px"}
          = f.label :title, "Título"
        .column.fixed{style: "width:500px"}
          %span= f.text_field :title, class: "inp"
      .columns.on-2
        .column.fixed{style: "width:200px"}
          = f.label :goal, "Dinero necesario"
        .column.fixed{style: "width:500px"}
          %span= f.number_field :goal, class: "inp"
      .columns.on-2
        .column.fixed{style: "width:200px"}
          = f.label :finish_date, "¿Para cuándo?"
        .column.fixed{style: "width:500px"}
          %span= f.date_select :finish_date
      .columns.on-2
        .column.fixed{style: "width:200px"}
          = f.label :category_id, "Área de interés"
        .column.fixed{style: "width:500px"}
          %span= f.collection_select :category_id, Category.all, :id, :name, class: "inp"
      .columns.on-2
        .column.fixed{style: "width:200px"}
          = f.label :why, "¿Por que necesitas la beca?", class: "h-100"
        .column.fixed{style: "width:500px"}
          %span.h-100= f.text_area :why, class: "h-100"
      .columns.on-2
        .column.fixed{style: "width:200px"}
          = f.label :dreams, "¿Cuáles son tus sueños?", class: "h-100"
        .column.fixed{style: "width:500px"}
          %span.h-100= f.text_area :dreams, class: "h-100"
      .columns.on-2
        .column.fixed{style: "width:200px"}
          = f.label :abilities, "¿Cuáles han sido tus logros ultimamente?", class: "h-100"
        .column.fixed{style: "width:500px"}
          %span.h-100= f.text_area :abilities, class: "h-100"
      .columns.on-2
        .column.fixed{style: "width:200px"}
          = f.label :better_country, "¿Cómo usarias esto para hacer de México un país mejor?", class: "h-100"
        .column.fixed{style: "width:500px"}
          %span.h-100= f.text_area :better_country, class: "h-100"
      .unit
        = f.submit "Registrar proyecto", class: "submit"

app/views/projects/_project.html.haml
.column.project
	.container
		= image_tag "circle_2.png", class: "image"
		%strong.name
			= project.student.full_name
		.info
			%h2
				= link_to project.title, project_path(project.id)
			%p
				= truncate project.student.bio, length: 100
			%p= link_to "Ver más >", project
		.bar
			.percentage
				.completed{style: "width:#{number_to_percentage project.current_percentage, precision: 0}"}
		%ul.data.unit
			%li.avance
				%strong= number_to_percentage project.current_percentage, precision: 0
				%br
				Avance
			%li.acumulado
				%strong= number_to_currency project.funded_count
				%br
				Acumulado
			%li.dias
				%strong= project.days_left
				%br
				Días restantes

app/views/projects/edit.html.haml
%h1 Projects#edit
%p Find me in app/views/projects/edit.html.haml

app/views/projects/index.html.haml
%h1.title
  Descubre nuevos <strong>proyectos</strong> y ayuda a cumplir los sueños de alguien

.columns.on-2
  .column.fixed{style: "width:720px"}
    .columns.on-3.projects
      - @projects.each do |project|
        = render project

      - if @projects.empty?
        .columns.projects.elastic-row-last{style: "width: 240px;"} &nbsp;

  .column.fixed{style: "width:190px"}
    .container.categories
      %ul
        %li
          %strong
            Populares
        %li
          %a{href: "#"}
            Más populares
        %li
          %a{href: "#"}
            Más nuevos
        %li
          %strong
            Categorias
        - Category.all.each do |category|
          %li
            %a{href: "#"}
              = category.name

app/views/projects/new.html.haml
%h1 Nuevo proyecto
= render 'form'

app/views/projects/show.html.haml
.show-proyecto
	%h1 
		= @project.title

	.columns.on-2
		.container.shadow
			.column.fixed{style: "width:610px"}
				.container.info.columns.on-2{style: "padding-right:20px;"}
					.column.fixed{style: "width: 240px;"}
						- if @project.student.provider.present?
							= image_tag @project.student.image, class: "avatar"
						- else
							= image_tag "avatar.png", class: "avatar"
					.column.fixed{style: "width: 350px"}
						%h2
							= @project.student.full_name
						.ubicacion
							%i.icon-map-marker
							= @project.student.city
							,
							= @project.student.state
						.category
							%i.icon-tags
							= @project.category.name
						.pitch
							= @project.student.bio
			.column.fixed{style: "width:260px"}
				.container.data
					%ul.data.unit
						%li.acumulado
							%strong= number_to_currency @project.funded_count
							%br
							Acumulado de #{number_to_currency @project.goal}
						%li.avance
							%strong= number_to_percentage @project.current_percentage, precision: 0
							%br
							Avance
						%li.dias
							%strong= @project.days_left
							%br
							Días restantes
					- if user_signed_in? and current_user.is_angel? 
						= form_for [@project, @fund] do |f|
							.unit{style: "margin-bottom:10px;"}
								= f.label :amount, "Cantidad"
								= f.number_field :amount, class: "cantidad"
							.unit
								= f.submit "Donar", class: "donar"
					- elsif user_signed_in?
						%a.donar
							Donar
					- else
						= link_to "Donar", new_angel_path, class: "donar"
					
	.columns.on-2.preguntas
		.container.shadow
			.column.fixed{style: "width:610px"}
				.container{style: "padding-right:20px;"}
					%h4
						¿Por quá quieres o necesitas una beca?
					%p
						= @project.why
					%h4
						¿Cuáles son tus sueños?
					%p= @project.dreams
					%h4
						¿Cuáles han sido tus logros ultimamente?
					%p= @project.abilities
					%h4
						¿Cómo usarias esto para hacer de México un país mejor?
					%p= @project.better_country
			
			.column.fixed{style: "width:260px"}
				.container.data
					%strong.rewards
						Aportaciones
					%ul.data.unit
						- 3.times do |t|
							%li
								%strong
									= "$ "+ (500*(t+1)).to_s
								%p
									Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
									tempor incididunt ut.

app/views/shared/_apoyalos.html.haml
.unit.apoyalos
  = image_tag "apoyalos.png"
  .circles
    - Project.limit(5).each do |project|
      .popper
        = image_tag "circle_1.png"
        .unit.pop
          .container
            .column.fixed.info{style: "width:234px;"}
              .container
                .mini_wrapper
                  %h3
                    = project.title
                  %p
                    = truncate project.student.bio
                .percentage
                  .completed{style: "width:#{number_to_percentage project.current_percentage, precision: 0}"}
            .column.fixed.data{style: "width:105px;"}
              %ul
                %li
                  %strong= number_to_percentage project.current_percentage, precision: 0
                  %br
                  Avance
                %li
                  %strong= number_to_currency project.funded_count
                  %br
                  Acumulado
                %li
                  %strong= project.days_left
                  %br
                  Días restantes
                %li
                  #{link_to "Ver Más", project_path(project)}

app/views/shared/_user_fields.html.haml
.unit
  = u.label :bio, "Biografía"
  = u.text_area :bio, rows: 4
.unit
  = u.label :email, "Correo electrónico"
  = u.email_field :email, class: "inp"
.unit
  = u.label :state, "Estado"
  = u.select :state, User::STATES
.unit
  = u.label :city, "Ciudad"
  = u.text_field :city, class: "inp"
%hr
.uni
  = u.label :password, "Contraseña"
  = u.password_field :password, class: "inp"
.unit
  = u.label :password_confirmation, "Confirmación de contraseña"
  = u.password_field :password_confirmation, class: "inp"

app/views/students/_form.html.haml
.unit
  .container.auth_wrapper
    = form_for @student do |f|
      .unit
        = f.label :name, "Nombre"
        = f.text_field :name, class: "inp"
      .unit
        = f.label :surname, "Apellidos"
        = f.text_field :surname, class: "inp"
      = f.fields_for :user do |u|
        = render partial: 'shared/user_fields', locals: { u: u }
      .unit
        = f.submit "Registrarme", class: "submit"

app/views/students/edit.html.haml
%h1 Editar perfil

.unit
  .container.auth_wrapper
    = form_for @student do |f|
      .unit
        = f.label :name, "Nombre"
        = f.text_field :name, class: "inp"
      .unit
        = f.label :surname, "Apellidos"
        = f.text_field :surname, class: "inp"
      = f.fields_for :user do |u|
        = render partial: 'shared/user_fields', locals: { u: u }
      .unit
        = f.submit "Actualizar datos", class: "submit"

app/views/students/new.html.haml
%h1 Crear cuenta de estudiante

= render 'form'

app/views/students/show.html.haml
%h1 Students#show
%p Find me in app/views/students/show.html.haml